service:                   robins-nest-designs-graphql

provider:
  name:                    aws
  runtime:                 nodejs8.10

plugins:
  - serverless-offline

custom:
  secrets:                 ${file(secrets.yml)}

functions:
  graphql:
    handler:               handler.handler
    environment:
      SQL_HOST:            ${self:custom.secrets.SQL_HOST}
      SQL_USER:            ${self:custom.secrets.SQL_USER}
      SQL_PWD:             ${self:custom.secrets.SQL_PWD}
      SQL_DB:              ${self:custom.secrets.SQL_DB}
      PAYPAL_CLIENTID:     ${self:custom.secrets.PAYPAL_CLIENTID}
      PAYPAL_CLIENTSECRET: ${self:custom.secrets.PAYPAL_CLIENTSECRET}
    events:
      - http:
          path:            graphql
          method:          ANY
          cors:            true
